# vim:sw=2:ts=2
name: ReviewDog test with 

# on events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:  # reusable workflow - the same jobs in submodules

jobs:
  clang-format:
    if: github.event_name == 'push'
    name: clang-format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 3  # current PR merge commit + 1 back

      - name: ReviewDog setup
        uses: reviewdog/action-setup@v1
        if: true

      - name: clang-format
        if: true
        shell: bash  # will enforce -o pipefail
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff -U0 HEAD^ | clang-format-diff-18 -p1 | /tmp/reviewdog -f=diff -f.diff.strip=0 -name=clang-format -reporter=github-check

  # reviewdog: use clang-format for PR review
  clang-format-pr:
    if: github.event_name == 'pull_request'
    name: clang-format-pr
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # current PR merge commit + 1 back

      - name: ReviewDog setup
        uses: reviewdog/action-setup@v1
        if: true

      - name: clang-format
        shell: bash  # will enforce -o pipefail
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff -U0 HEAD^ | clang-format-diff-18 -p1 | /tmp/reviewdog -f=diff -f.diff.strip=0 -name=clang-format-pr -reporter=github-pr-review -fail-on-error

